sadang-boogi/howread-back

.github/CODEOWNERS
=> chore: auto assign 활성화

src/main/java/com/rebook/domain/entity/BookEntity.java, src/main/java/com/rebook/repository/BookRepository.java, src/main/resources/application.yml, src/test/java/com/rebook/repository/BookRepositoryTest.java
- 샘플 Repository 단위 테스트
- application.yml에 test profile 추가
- `@DataJpaTest` 사용 예시 추가
=> test(repository): Repository 단위 테스트 추가

build.gradle, src/main/java/com/rebook/RebookApplication.java, src/main/java/com/rebook/common/domain/BaseEntity.java, src/main/java/com/rebook/review/controller/ReviewController.java, src/main/java/com/rebook/review/domain/Review.java, src/main/java/com/rebook/review/domain/ReviewEntity.java, src/main/java/com/rebook/review/dto/ReviewRequest.java, src/main/java/com/rebook/review/dto/ReviewResponse.java, src/main/java/com/rebook/review/repository/ReviewRepository.java, src/main/java/com/rebook/review/service/ReviewService.java, src/test/java/com/rebook/review/service/ReviewServiceTest.java
1. ReviewEntity starRate 범위 수정
2. ReviewService - 리뷰 저장 및 리스트 조회 구현
3. ReviewController - 리뷰 저장 및 리스트 조회 구현
=> Review 저장 구현

src/main/java/com/rebook/book/controller/BookController.java, src/main/java/com/rebook/book/domain/BookEntity.java, src/main/java/com/rebook/book/dto/response/BookResponse.java, src/main/java/com/rebook/book/service/BookService.java, src/test/java/com/rebook/book/service/BookServiceTest.java
refactor: Book 저장 후, BookResponse가 반환되도록 수정
=> refactor: Book 리팩토링

src/main/java/com/rebook/book/domain/entity/BookEntity.java
=> feat: Cascade 옵션 추가

src/main/java/com/rebook/book/controller/BookController.java, src/main/java/com/rebook/book/controller/request/BookCreateRequest.java, src/main/java/com/rebook/common/exception/BadRequestException.java, src/main/java/com/rebook/common/exception/CommonExceptionHandler.java, src/main/java/com/rebook/common/exception/ExceptionCode.java, src/test/java/com/rebook/book/controller/BookControllerTest.java, src/test/java/com/rebook/book/domain/BookEntityTest.java
=> test: BookController 테스트 코드 작성

src/main/java/com/rebook/user/util/GoogleOAuthService.java
Encoded된 형태
`4%2F0Adeu5BXSr6ULvZ92_2UNEUpsqKplv7lMu66sSLCRZVEfNwN14hbvQtS7uS1cVtyw5fqsGw`
Decoded된 형태
`4/2F0Adeu5BXSr6ULvZ92_2UNEUpsqKplv7lMu66sSLCRZVEfNwN14hbvQtS7uS1cVtyw5fqsGw`
=> fix(oauth): 구글 AuthorizationCode는 URL Encoded된 형태이므로 Decode 후에 처리합니다.

src/main/java/com/rebook/book/controller/BookController.java, src/main/java/com/rebook/hashtag/controller/HashtagController.java
그동안 추가를 미뤄두었던 Swagger를 추가했습니다.
=> feat: swagger 추가

src/main/resources/db/migration/V3__add_isbn_field_to_book.sql
=> refactor: flyway sql 수정

src/main/java/com/rebook/RebookApplication.java, src/main/java/com/rebook/common/domain/CorsProperties.java
=> fix: CorsProperties에서 NPE 발생하는 오류 수정

src/main/java/com/rebook/jwt/JwtUtil.java, src/main/java/com/rebook/jwt/dto/JwtPayload.java, src/main/java/com/rebook/user/service/dto/AuthClaims.java, src/test/java/com/rebook/book/controller/BookControllerTest.java
1. email, name 등의 클레임은 삭제
2. JwtPayload 클래스로 페이로드 파싱
=> Feat : jwt payload 클래스로 파싱

src/main/java/com/rebook/review/repository/ReviewRepository.java, src/main/java/com/rebook/review/service/ReviewService.java, src/test/java/com/rebook/review/service/ReviewServiceTest.java
=> Fix : review query

src/main/java/com/rebook/studygroup/domain/StudyGroupEntity.java, src/main/java/com/rebook/studygroup/domain/StudyGroupMemberEntity.java, src/main/java/com/rebook/studygroup/domain/StudyGroupMemberGrade.java, src/main/java/com/rebook/studygroup/domain/StudyGroupMemberRole.java, src/main/resources/db/migration/V5__create_studygroup_table.sql
- 스터디그룹의 필드는 id(식별자), name(스터디명), leader_id(FK-스터디 리더 user의 id), max_members(최대 인원수)입니다.
=> feat(study-group): StudyGroupEntity 생성 및 Flyway에서 사용하는 DDL 생성

.github/workflows/deploy.yml
=> refactor(CI/CD): 스크립트 수정

src/main/java/com/rebook/common/exception/ExceptionCode.java, src/main/java/com/rebook/image/controller/ImageController.java, src/main/java/com/rebook/image/controller/response/ImageResponse.java, src/main/java/com/rebook/image/domain/ImageEntity.java, src/main/java/com/rebook/image/domain/ImageFile.java, src/main/java/com/rebook/image/exception/ImageException.java, src/main/java/com/rebook/image/repository/ImageRepository.java, src/main/java/com/rebook/image/service/ImageService.java, src/main/java/com/rebook/image/service/ImageUploader.java, src/main/java/com/rebook/image/service/dto/ImageDto.java
1. **`ImageFile` 추가** 
2. **S3에 이미지 업로드 후 Image 테이블에 이미지 Url 저장**
=> feat : S3에 Image 업로드 후 DB 저장

src/main/resources/db/migration/V10__add_base_entity_column_to_reaction_table.sql
reaction 테이블에 BaseEntity의 누락된 칼럼 추가
=> feat : Reaction 테이블에 BaseEntity 칼럼 추가

src/main/java/com/rebook/common/exception/ExceptionCode.java, src/main/java/com/rebook/user/controller/request/UserUpdateRequest.java, src/main/java/com/rebook/user/domain/UserEntity.java, src/main/java/com/rebook/user/service/UserService.java, src/main/java/com/rebook/user/service/command/UserUpdateCommand.java, src/test/java/com/rebook/review/service/ReviewServiceTest.java
**ImageId로 User avatar 이미지 추가**
=> feat : User의 avatar 이미지 추가

src/main/java/com/rebook/common/config/WebMvcConfig.java, src/main/java/com/rebook/common/exception/ExceptionCode.java, src/main/java/com/rebook/reaction/controller/response/ReactionResponse.java, src/main/java/com/rebook/reaction/domain/ReactionEntity.java, src/main/java/com/rebook/reaction/domain/ReactionType.java, src/main/java/com/rebook/reaction/repository/ReactionRepository.java, src/main/java/com/rebook/reaction/service/ReactionService.java, src/main/java/com/rebook/reaction/service/dto/ReactionDto.java, src/main/java/com/rebook/reaction/util/StringToReactionTypeConverter.java, src/main/java/com/rebook/reaction/util/StringToTargetTypeConverter.java
1. **리액션 키기**
- 리액션이 없는 경우 -> `ReactionEntity`을 생성하여 저장
- 리액션이 존재하지만 꺼져 있는 경우 -> `reactionEntity.turnOn()`으로 해당 리액션을 활성화
2. **리액션 끄기**
- 리액션이 켜져 있는 경우 -> `reactionEntity.turnOff()` 으로 해당 리액션 리액션을 비활성화
=> feat : Reaction Service 추가

src/main/java/com/rebook/studygroup/controller/StudyGroupController.java, src/main/java/com/rebook/studygroup/repository/StudyGroupRepository.java, src/main/java/com/rebook/studygroup/service/StudyGroupService.java, src/test/java/com/rebook/studygroup/service/StudyGroupServiceTest.java
=> feat: StudyGroup 목록 조회 API 추가

src/main/java/com/rebook/book/controller/BookController.java, src/main/java/com/rebook/book/controller/response/BookReactionResponse.java, src/main/java/com/rebook/book/controller/response/BookResponse.java, src/main/java/com/rebook/book/service/BookService.java, src/main/java/com/rebook/book/service/dto/BookDto.java, src/main/java/com/rebook/book/service/dto/BookReactionDto.java, src/main/java/com/rebook/reaction/repository/ReactionRepository.java, src/test/java/com/rebook/book/controller/BookControllerTest.java, src/test/java/com/rebook/book/service/BookServiceTest.java
- 사용자의 리액션 정보를 `Book`에 list로 추가
=> feat : Book 조회 시 사용자 reaction 추가
